#url: http://servicos.saude.ce.gov.br/diretrizes
github: SaudeCE

collections:
  - plays

permalink: pretty
highlighter: rouge
#url: https://playbook.cio.gov

collections:
  - plays

markdown: kramdown

sass:
    sass_dir: assets/_sass
